# Generated by Django 2.0.5 on 2018-07-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='experiment',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='window_start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
