# Generated by Django 2.0.7 on 2018-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(db_index=True, max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('stamp', models.DateTimeField(db_index=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
