# Generated by Django 2.1.7 on 2019-02-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='point',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='metric',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
