# Generated by Django 2.2 on 2019-05-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190213_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enroll_failed_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='graduate_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='unenroll_failed_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='update_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='update_failed_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
